FROM httpd:latest

COPY apache.dev.conf /usr/local/apache2/conf/apache.dev.conf
# httpd.confにカスタム設定ファイルを読み込む行を追加
RUN echo "Include conf/apache.dev.conf" >> /usr/local/apache2/conf/httpd.conf

# mod_proxyとmod_proxy_httpモジュールを有効にする
RUN sed -i 's/#LoadModule proxy_module modules\/mod_proxy.so/LoadModule proxy_module modules\/mod_proxy.so/' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/#LoadModule proxy_http_module modules\/mod_proxy_http.so/LoadModule proxy_http_module modules\/mod_proxy_http.so/' /usr/local/apache2/conf/httpd.conf

EXPOSE 80

CMD ["httpd-foreground"]
